name: Translate
on: workflow_dispatch
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read 'en.json' content
        id: translation_base
        run: |
          content=`cat ./en.json`
          # the following lines are only required for multi line json
          content="${content//'%'/''}"
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          # end of optional handling for multi line json
          echo "enJSON=$content" >> $GITHUB_OUTPUT
      # - name: Print 'en.json' content
      #   run: echo "${{steps.translation_base.outputs.enJSON}}"
      - name: Invoke custom translation lambda function
        id: translation_lambda
        uses: gagoar/invoke-aws-lambda@v3.3.1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.REGION }}
          FunctionName: "translate-files"
          # Payload: ${{steps.translation_base.outputs.enJSON}}
          Payload: ${{ format('{{"sourceLang":{0}, "targetLang":{1}, "data":{2}}}', '"en"', '"fi"', steps.translation_base.outputs.enJSON) }}
      - name: Echo response Payload
        run: echo ${{ fromJSON(steps.translation_lambda.outputs.response).Payload }}
      # - name: Git config
      #   run: |
      #     git config user.name ${{github.actor}}
      #     git config user.email ${{github.actor}}@users.noreply.github.com
